AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

Lint/DuplicateMethods:
  Enabled: true

Naming/MethodParameterName:
  MinNameLength: 1
  AllowedNames:
    - a
    - b
    - io
    - id

Naming/PredicateMethod:
  Enabled: false
